[package]
name = "microcosm-links"
description = "Link extraction for atproto records"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
default = ["json"]
json = ["dep:tinyjson"]

[dependencies]
fluent-uri = "0.3.2"
thiserror = "2.0.9"
tinyjson = { version = "2.5.1", optional = true }
