name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build lib
      run: cargo build --verbose
    - name: Check (default features)
      run: cargo check
    - name: Run tests
      run: cargo test --all-features --verbose

  style:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: get nightly toolchain for jetstream fmt
        run: rustup toolchain install nightly --allow-downgrade -c rustfmt
      - name: fmt
        run: cargo fmt --package links --package constellation --package ufos --package spacedust --package who-am-i --package slingshot --package pocket -- --check
      - name: fmt jetstream (nightly)
        run: cargo +nightly fmt --package jetstream -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
